name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: ['8.0']
        report-coverage: [false]
        psalm-flags: ['']
        include:
          - php: '7.2'
            report-coverage: true
            psalm-flags: '--shepherd'

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, soap

    - name: Validate composer.json
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPStan
      run: composer run-script lint:ci

    - name: Run PSalm
      run: vendor/bin/psalm ${{ matrix.psalm-flags }}

    - name: Unit Tests
      run: vendor/bin/phpunit --exclude-group manual --coverage-clover clover.xml

    - uses: codecov/codecov-action@v1
      if: ${{ matrix.report-coverage }}
      with:
        file: ./clover.xml
        flags: unittests
        name: codecov-greenter

